apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: costoptimize
  labels:
    app: backend
    app.kubernetes.io/part-of: costoptimize-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: costoptimize/backend:prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: costoptimize-config
            - secretRef:
                name: costoptimize-secrets
          env:
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: costoptimize-config
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: costoptimize-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: costoptimize-secrets
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
